const passwordActionType = {
  PASSWORDGENERATE: "PASSWORDGENERATE",
  GETALLPASSWORD: "GETALLPASSWORD",
  EDITWPM: "EDDITWPM",
  DELETEWPM: "DELETEWPM",
  GETEDIT: "GETEDIT",
};

export default passwordActionType;
